"""
Stage 3: Multi-dimensional reward function for FIPO RL.

Plugs into veRL's reward_manager (dapo mode) via:
    reward_model.reward_manager=dapo
    # custom_reward_fn path registered separately in veRL config

Components:
    +1.0  - JSON parseable + all required fields present
    +2.0  - violation label matches ground truth (when available)
    -0.5  - reason doesn't reference any extracted attribute (hallucination proxy)
    +RM   - learned reward model score (Stage 2 output)
    -3.0  - JSON parse failure (early exit)
    -2.0  - missing required fields

This module can be imported as a standalone function or used through
the veRL custom reward interface.
"""
from __future__ import annotations

import json
from typing import Any, List, Optional

REQUIRED_KEYS = frozenset({"category", "attributes", "violation", "reason"})


def compute_reward(
    output_text: str,
    *,
    image: Optional[Any] = None,
    gt_annotation: Optional[dict] = None,
    rm_model=None,
) -> float:
    """
    Compute scalar reward for a single rollout response.

    Args:
        output_text:   Raw text generated by the policy model.
        image:         PIL image (for RM scorer, optional).
        gt_annotation: Ground-truth dict with at least {"violation": bool}.
        rm_model:      Trained reward model with .score(image, text) -> float.

    Returns:
        Scalar reward in roughly [-3, 5] range.
    """
    # ------------------------------------------------------------------
    # 1. JSON format correctness
    # ------------------------------------------------------------------
    text = output_text.strip()
    # Strip markdown fences if model wraps output
    if text.startswith("```"):
        lines = text.splitlines()
        text = "\n".join(lines[1:-1] if lines[-1].strip() == "```" else lines[1:])

    try:
        parsed = json.loads(text)
    except json.JSONDecodeError:
        return -3.0  # Hard penalty; FIPO will down-weight this token path

    if not REQUIRED_KEYS.issubset(parsed.keys()):
        return -2.0

    reward = 1.0  # Base: parseable + complete structure

    # ------------------------------------------------------------------
    # 2. Violation label accuracy (supervised signal)
    # ------------------------------------------------------------------
    if gt_annotation is not None:
        gt_violation = bool(gt_annotation.get("violation", False))
        pred_violation = bool(parsed.get("violation", False))
        if pred_violation == gt_violation:
            reward += 2.0

    # ------------------------------------------------------------------
    # 3. Hallucination proxy: reason must cite ≥1 extracted attribute
    # ------------------------------------------------------------------
    attr_keys = set(parsed.get("attributes", {}).keys())
    reason_text = parsed.get("reason", "")
    if attr_keys and not any(k in reason_text for k in attr_keys):
        reward -= 0.5

    # ------------------------------------------------------------------
    # 4. Learned reward model score
    # ------------------------------------------------------------------
    if rm_model is not None and image is not None:
        rm_score = rm_model.score(image, output_text)
        reward += float(rm_score)

    return reward


# ---------------------------------------------------------------------------
# veRL batch interface (list of responses → list of rewards)
# ---------------------------------------------------------------------------

def batch_compute_reward(
    output_texts: List[str],
    gt_annotations: Optional[List[Optional[dict]]] = None,
    rm_model=None,
) -> List[float]:
    if gt_annotations is None:
        gt_annotations = [None] * len(output_texts)
    return [
        compute_reward(text, gt_annotation=ann, rm_model=rm_model)
        for text, ann in zip(output_texts, gt_annotations)
    ]
